# Site settings é…ç½®ç«™ç‚¹
title: 'æ³¥'
description: 'Javaã€Springã€Nginxã€Centosã€Oracleã€Mysql'
keywords: 'æ³¥ã€Java'
url: 'https://GorgeousNi.github.io' # your host

# nav ä¸­æ–‡å­—ç¬¦ç©ºæ ¼ï¼š&emsp;
nav: # æœ€ä½³ä½“éªŒ å…­ä¸ªæ ‡ç­¾ ä¸”æœ€å¥½æ¯ä¸ªæ ‡ç­¾ä¸è¶…è¿‡4ä¸­æ–‡å­—
  é¦–é¡µ: '/'
  æ ‡ç­¾: '/tags.html'
  æ—¶é—´çº¿: '/timeline.html'
  å…³äºåšä¸»: '/about.html'
  å‹æƒ…é“¾æ¥: '/friendLink.html'

# åšä¸»
author: true
name: 'æ³¥'
NickName: 'GorgeousNi'
webtitle: 'æ³¥ã€Java'
bio: 'ç¨€é¥­ã€è›‹ç³•å’–å•¡å®‰é™ä¸ä½ '
about: true
aboutyou: '&emsp;&emsp;æ³¥å‘€ï¼Œæ€§åˆ«å¥³ï¼›çˆ±å¥½ç”·ï¼›å–œæ¬¢ç”œå“ï¼›åˆå»ºåšå®¢ï¼Œæ„Ÿè°¢[<a href="https://github.com/xukimseven/HardCandy-Jekyll">HardCandy-Jekyll</a>]ï¼Œæ„Ÿè°¢å„è·¯å¼€æºå¤§ç¥ï¼Œä»¥åä¼šä¸»åŠ›å†™æˆ‘çš„åšå®¢ï¼Œå¸Œæœ›ä¹Ÿå¯ä»¥æœ‰å€¼å¾—åˆ†äº«çš„ä¸œè¥¿è¢«å¤§å®¶starå’Œè®¨è®ºï¼›</br>
&emsp;&emsp;ä¸€åJavaç å†œï¼Œå–œæ¬¢å¥½çœ‹çš„ä»£ç ï¼›è™½ç„¶æ˜¯ä¸€ååç«¯ï¼Œä¸ä¼šç¾æœ¯ã€äº”éŸ³ä¸å…¨(æˆ–è€…è¯´æ²¡æœ‰ä»€ä¹ˆè‰ºæœ¯å¤©åˆ†)ï¼Œä½†æ˜¯å–œæ¬¢æœ‰è¶£çš„äº‹ï¼Œå–œæ¬¢æœ‰è¶£çš„äººï¼Œå–œæ¬¢çœ‹ä¹¦ã€çœ‹åšå®¢ã€å¬éŸ³ä¹ã€çœ‹LOLæ¯”èµ›ã€çœ‹ç»¼è‰ºï¼Œå—¯ï½æœ€ç¨€é¥­çš„æ˜¯å‘¨äº”ï½
è¨€è€Œæ€»ä¹‹ï¼Œä¸ç²¾è‡´çš„ğŸ·æœ‰ç€ä¸€é¢—æƒ³è¦ç²¾è‡´çš„å¿ƒï¼›æ¯•ç«Ÿç”Ÿæ´»è¿˜æ˜¯è¦å¤šæŠ˜è…¾æŠ˜è…¾ï¼Œæ‰èƒ½åˆ·æ–°ç‚¹è‡ªå·±çš„å­˜åœ¨æ„Ÿï½å–œæ¬¢å’ŒèŠçš„æ¥çš„äººäº¤æœ‹å‹(è™½ç„¶æˆ‘äº¤é™…åœˆå¾ˆçª„ï¼Œå¯è§è·Ÿæˆ‘èŠçš„æ¥çš„ä½ å¯¹æˆ‘å¤šä¹ˆé‡è¦ï½)</br>
&emsp;&emsp;ä¸€è·¯ä¸Šèµ°èµ°åœåœã€ä¸å¤Ÿå¥½ï¼Œä½†æœ‰é¢—æƒ³è¦å˜å¥½çš„å¿ƒï¼›æ„Ÿè°¢å…¬å¸çš„åŒäº‹ï¼Œé‡åˆ°çš„æœ‹å‹ï¼Œæ•™ä¼šæˆ‘å¾ˆå¤šçŸ¥è¯†å‘¢ã€‚<a>ä¸å¿˜åˆå¿ƒã€æ–¹å¾—å§‹ç»ˆï¼›</a>'
portraits: '/assets/profile.jpeg' # your portraits image file path



# SNS
SNS: true
SNS-icon: #['Facebook', 'weibo', 'qq', 'github', 'Dribbble', 'Twitter', 'instagram', 'weixin', 'Codepen']
  mail: 'mailto:gorgeousni@qq.com'
  weixin: '/assets/wechat.jpeg' # ä½ çš„å¾®ä¿¡äºŒç»´ç å­˜æ”¾çš„åœ°å€
  qq: '/assets/qq.jpeg' # ä½ çš„qqäºŒç»´ç å­˜æ”¾çš„åœ°å€ or http://wpa.qq.com/msgrd?v=3&uin='1689857538'&site=qq&menu=yes
  github: 'https://github.com/GorgeousNi'
 # Codepen: ''
  weibo: 'https://weibo.com/2829309103/profile?rightmod=1&wvr=6&mod=personinfo'
 # instagram: ''
 # Twitter: ''
 # Dribbble: ''
 # Facebook: ''
 # Google: ''
 # zhihu: ''
 # juejin: ''
 # twitch: ''

# åˆ†é¡µ
paginate: 3
paginatepath: ['page:num']

# since
footer:
  since: 2018

# Markdown
markdown: kramdown
kramdown:
  input: GFM
# ä»£ç é«˜äº® ä½¿ç”¨rouge
highlighter: rouge
# ä»£ç é«˜äº®ä¸»é¢˜ä½¿ç”¨pygmentsä¸»é¢˜: autumn\ default\ emacs\ friendly\ manni\ murphy\ pastie\ perldoc\ tango ä»»é€‰ä¸€ä¸ªä½ å–œæ¬¢çš„ä¸»é¢˜åç§°å¡«åœ¨ä¸‹é¢çš„å•å¼•å·ä¸­
pygmentsTheme: 'default'

# å‹æƒ…é“¾æ¥
friends:
  Captain Little: 'https://binarycaptain.github.io/'

# è¯„è®º æœ€ä½³ä½“éªŒ åœ¨disqusã€livereå’ŒGitmentä¹‹é—´ä¸‰é€‰ä¸€
# disqus è¯„è®º
disqus: false
disqus_url: '' # https://abc.disqus.com/embed.js
# æ¥å¿…åŠ›è¯„è®º
livere: false
livere_uid: 'MTAyMC8zNDI2OS8xMDgwNg==' # MTAyMC8zNDI2OS8xMDgwNg==
# Gitmentè¯„è®º OAuth Application
Gitment: true
Gitment_owner: 'GorgeousNi'  # githubç”¨æˆ·å
Gitment_repo: 'GorgeousNi.github.io'  # githubåšå®¢å­˜æ”¾çš„ä»“åº“å
client_id: '63b3d4c0e45a6706a8d9'  # æ³¨å†Œ OAuth Application åè·å¾—çš„ client_id
client_secret: '9aa8950b462be87f4133347468fd6368f3c568e5'  # æ³¨å†Œ OAuth Application åè·å¾—çš„ client_secret

# Share : weibo, qq, wechat, tencent, douban, qzone, linkedin, diandian, facebook, twitter, google
social-share: true
social-share-items: ['qq', 'wechat', 'weibo', 'twitter', 'facebook']

# ç™¾åº¦ç»Ÿè®¡ åœ¨baidu-urlé‡Œå¡«å†™è‡ªå·±ç›¸å…³çš„urlä»£ç 
baidu: true
baidu-url: '5c6697f44a73d09b4a6e8f5d2c659537'
# è°·æ­Œåˆ†æ åœ¨google-IDé‡Œå¡«å†™è‡ªå·±åœ¨è°·æ­Œåˆ†æè·å¾—çš„è¿½è¸ªID
google: false
google-ID: ''

# åšå®¢å¤´ä¿¡æ¯å¤‡é€‰é¢œè‰²ï¼ˆè¯¥éƒ¨åˆ†åœ¨ç«™ç‚¹ä¸­ä¸å……å½“ç«™ç‚¹å˜é‡ï¼Œå°†å…¶å†™åœ¨postçš„å¤´ä¿¡æ¯ä¸­ç”¨æ¥å……å½“é¡µé¢å˜é‡ï¼‰
color: rgb(154,133,255) rgb(255,90,90) rgb(255,210,32) rgb(98,170,255)

theme: jekyll-theme-cayman